### ISSUE TITLE
Ignoring subdirectories by name/pattern

### ISSUE THREAD

**Issue by Felix-El** [colcon/colcon-recursive-crawl#13]
Hi there,

I hope this is the right place to ask.
I'm maintaining some proprietary ROS1 and ROS2 packages which live in close proximity in a directory structure.
When building with colcon for ROS1, I'd like to ignore any subfolder named "ros2" and vice versa.
I cannot change the directory structure with major pain because the workspace is scattered over various Git submodules, each with their respective owners.
If there is no such option in colcon, yet, I'd be happy to add it. Hope you can give me a pointer where/how to integrate this exclusion mechanism.

(Any link to discussions related to having ROS1/ROS2 side-by-side is also much appreciated!)

Best Regards

Felix

**Comment by dirk-thomas** [comment]
Atm there is no explicit option for ignoring packages based on a regex matching their path.

Based on your description I assume there is no other feature which distinguishes these ROS 1 and ROS 2 packages? Also does the superset of packages still have unique names or do some have the same name? The later would be problematic for options like `--packages-select` / `--packages-skip` which operate on names alone. In this case you really want to *ignore* packages during the discovery phase.

You could certainly achieve this using a `colcon list` call, filtering lines with grep, selecting the package name from each line`, and feeding the list of undesired packages to `--packages-ignore`.

To make this more streamlines you could add a new option (e.g. `--packages-ignore-path-regex`) which would be similar to [--packages-ignore-regex](https://github.com/colcon/colcon-package-selection/blob/9a2b614da9749d6d5922a92fc389c50964ed5986/colcon_package_selection/package_discovery/ignore.py#L29-L32) but would operate on the path rather than the name.

If you always build the same set of packages you could also simply hard code the list of packages in both cases and put thjose lists into a custom [mixin](https://github.com/colcon/colcon-mixin-repository/) to trigger either by name.

**Comment by Felix-El** [comment]
Hello Dirk,

thank you very much for sharing your thoughts on this.
It might be possible to add a suffix to distinguish between ROS1/2. I have not seen any recommendations on how to do this anywhere.

If we rename the packages so they can be filtered more easily, colcon list / --packages-ignore would certainly do.

Otherwise we could, as you propose, use mixins. I was totally unaware of that feature but it sounds very promising. I believe this is the better approach and also gives more granular control over the CMake build options. Great!
